/**
 * Dashboards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ChangeType = 'Creation' | 'Modification' | 'Removal';

export const ChangeType = {
    Creation: 'Creation' as ChangeType,
    Modification: 'Modification' as ChangeType,
    Removal: 'Removal' as ChangeType
};

