/**
 * Dashboards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChangeSetEntryRefData } from './change-set-entry-ref-data.model';
import { UserRef } from './user-ref.model';


export interface ChangeSetData { 
    id?: string;
    label?: string | null;
    timestamp?: string;
    updatedBy?: UserRef;
    entries?: Array<ChangeSetEntryRefData> | null;
}

