/**
 * Dashboards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiError } from './api-error.model';
import { DiscordInsightsAnalytics } from './discord-insights-analytics.model';


export interface DiscordInsightsAnalyticsApiContract { 
    error?: ApiError;
    payload?: DiscordInsightsAnalytics;
}

