/**
 * Dashboards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JoinBySourceDiscordInsightsData } from './join-by-source-discord-insights-data.model';
import { LeaversDiscordInsightsData } from './leavers-discord-insights-data.model';
import { ActivationDiscordInsightsData } from './activation-discord-insights-data.model';
import { OverviewDiscordInsightsData } from './overview-discord-insights-data.model';
import { MembershipDiscordInsightsData } from './membership-discord-insights-data.model';
import { RetentionDiscordInsightsData } from './retention-discord-insights-data.model';


export interface DiscordInsightsAnalytics { 
    joinBySource?: Array<JoinBySourceDiscordInsightsData> | null;
    membership?: Array<MembershipDiscordInsightsData> | null;
    leavers?: Array<LeaversDiscordInsightsData> | null;
    activation?: Array<ActivationDiscordInsightsData> | null;
    retention?: Array<RetentionDiscordInsightsData> | null;
    overview?: Array<OverviewDiscordInsightsData> | null;
}

