/**
 * Dashboards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormSectionData } from './form-section-data.model';
import { FormThemeSettings } from './form-theme-settings.model';
import { FormSettings } from './form-settings.model';


export interface FormData { 
    id?: number;
    dashboardId?: string;
    settings?: FormSettings;
    theme?: FormThemeSettings;
    sections?: Array<FormSectionData> | null;
}

