/**
 * Dashboards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AverageVisitorsStats } from './average-visitors-stats.model';
import { Int32ValueDiff } from './int32-value-diff.model';
import { IncomeStatsItem } from './income-stats-item.model';
import { SingleValueDiff } from './single-value-diff.model';
import { DecimalValueDiff } from './decimal-value-diff.model';
import { VisitorsStats } from './visitors-stats.model';


export interface GeneralAnalytics { 
    aggregatedAt?: string;
    totalRevenue?: DecimalValueDiff;
    totalUsers?: Int32ValueDiff;
    keysSold?: Int32ValueDiff;
    retentionRate?: SingleValueDiff;
    visitors?: VisitorsStats;
    avgLiveViews?: AverageVisitorsStats;
    income?: Array<IncomeStatsItem> | null;
}

