/**
 * Dashboards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GlobalSearchResult } from './global-search-result.model';


export interface GlobalSearchPagedList { 
    readonly isEmpty?: boolean;
    readonly isFirst?: boolean;
    readonly isLast?: boolean;
    readonly pageIndex?: number;
    readonly limit?: number;
    readonly totalElements?: number;
    readonly totalPages?: number;
    readonly content?: Array<GlobalSearchResult> | null;
    readonly count?: number;
    readonly licensesCount?: number;
    readonly releasesCount?: number;
}

