/**
 * Dashboards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KeyOwnerSummaryData } from './key-owner-summary-data.model';


export interface LicenseKeySummaryData { 
    id?: number;
    user?: KeyOwnerSummaryData;
    planId?: number;
    expiry?: string;
    value?: string | null;
    reason?: string | null;
    trialEndsAt?: string;
    unbindableAfter?: string;
}

