/**
 * Dashboards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PlanData { 
    id?: number;
    dashboardId?: string;
    productId?: number;
    amount?: number;
    currency?: string | null;
    subscriptionPlan?: string | null;
    licenseLife?: string | null;
    description?: string | null;
    unbindableDelay?: string | null;
    isTrial?: boolean;
    discordRoleId?: number;
}

