/**
 * Dashboards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductFeatureData } from './product-feature-data.model';
import { IBinaryData } from './i-binary-data.model';


export interface ProductData { 
    id?: number;
    dashboardId?: string;
    name?: string | null;
    description?: string | null;
    images?: Array<string> | null;
    downloadUrl?: string | null;
    imageUrl?: string | null;
    logoUrl?: string | null;
    iconUrl?: string | null;
    slug?: string | null;
    version?: string | null;
    discordRoleId?: number;
    discordGuildId?: number;
    checkoutsTrackingWebhookUrl?: string | null;
    features?: Array<ProductFeatureData> | null;
    uploadedImage?: IBinaryData;
    uploadedLogo?: IBinaryData;
    uploadedIcon?: IBinaryData;
    uploadedImages?: Array<IBinaryData> | null;
}

