/**
 * Dashboards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IBinaryData } from './i-binary-data.model';


export interface ProductFeatureData { 
    icon?: string | null;
    uploadedIcon?: IBinaryData;
    title?: string | null;
    desc?: string | null;
}

