/**
 * Dashboards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReleaseType } from './release-type.model';


export interface ReleaseData { 
    id?: number;
    planId?: number;
    title?: string | null;
    initialStock?: number;
    type?: ReleaseType;
    isActive?: boolean;
    password?: string | null;
}

