/**
 * Dashboards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ReleasesSortBy = 'Newest' | 'Oldest' | 'Stock';

export const ReleasesSortBy = {
    Newest: 'Newest' as ReleasesSortBy,
    Oldest: 'Oldest' as ReleasesSortBy,
    Stock: 'Stock' as ReleasesSortBy
};

