/**
 * Dashboards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Int32ValueDiff } from './int32-value-diff.model';
import { VisitorsStatsItem } from './visitors-stats-item.model';


export interface VisitorsStats { 
    count?: Int32ValueDiff;
    data?: Array<VisitorsStatsItem> | null;
}

