export * from './analytics.service';
import { AnalyticsService } from './analytics.service';
export * from './audit.service';
import { AuditService } from './audit.service';
export * from './bots-license-keys.service';
import { BotsLicenseKeysService } from './bots-license-keys.service';
export * from './countries.service';
import { CountriesService } from './countries.service';
export * from './dashboards.service';
import { DashboardsService } from './dashboards.service';
export * from './form-values.service';
import { FormValuesService } from './form-values.service';
export * from './forms.service';
import { FormsService } from './forms.service';
export * from './global-search.service';
import { GlobalSearchService } from './global-search.service';
export * from './license-keys.service';
import { LicenseKeysService } from './license-keys.service';
export * from './member-role-bindings.service';
import { MemberRoleBindingsService } from './member-role-bindings.service';
export * from './member-roles.service';
import { MemberRolesService } from './member-roles.service';
export * from './payments.service';
import { PaymentsService } from './payments.service';
export * from './permissions.service';
import { PermissionsService } from './permissions.service';
export * from './plans.service';
import { PlansService } from './plans.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './releases.service';
import { ReleasesService } from './releases.service';
export * from './stripe-web-hooks.service';
import { StripeWebHooksService } from './stripe-web-hooks.service';
export * from './time-zones.service';
import { TimeZonesService } from './time-zones.service';
export * from './updates.service';
import { UpdatesService } from './updates.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AnalyticsService, AuditService, BotsLicenseKeysService, CountriesService, DashboardsService, FormValuesService, FormsService, GlobalSearchService, LicenseKeysService, MemberRoleBindingsService, MemberRolesService, PaymentsService, PermissionsService, PlansService, ProductsService, ReleasesService, StripeWebHooksService, TimeZonesService, UpdatesService, UsersService];
