version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - ./env/psql/data:/var/lib/postgresql/data
      - ./env/psql/dumps:/db_dumps
    environment:
      POSTGRES_USER: profiles
      POSTGRES_PASSWORD: profiles
      POSTGRES_DB: profiles
  webapi:
    image: registry.gitlab.com/resolff/vladyk-lukyanenko/paste/api:latest
    restart: on-failure
    environment:
      EntityFramework:MigrateDatabaseOnStart: "true"
      DataSource:PostgresConnectionString: "Server=db;Port=5432;Username=profiles;Password=profiles;Database=profiles;"
      ASPNETCORE_URLS: "http://*:80"
      Kestrel:Certificates:Development:Password: 1234567890
    ports:
      - 5000:80
    volumes:
      - ./logs/api:/profiles-api-logs
      - ./NLog.config:/app/NLog.config
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
      - ./sslsvalidation:/app/wwwroot/.well-known/pki-validation:ro
    depends_on:
      - db
  webspa:
    image: registry.gitlab.com/resolff/vladyk-lukyanenko/paste/spa:latest
    restart: on-failure
    environment:
      ASPNETCORE_URLS: "http://*:80"
      Kestrel:Certificates:Development:Password: 1234567890
    ports:
      - 5001:80
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/